import "./globals.scss";
import { Inter } from "next/font/google";
import { ThemeContextProvider } from "@context/context";
import Navbar from "@components/Navbar/Navbar";
import Footer from "@components/Footer";

const inter = Inter({ subsets: ["cyrillic"], weights: ["400", "500", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <Navbar />
          <div className="content">
            <main>{children}</main>
            <Footer />
          </div>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
